---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    servicepath: "/turbine.stream"
  labels:
    project: "${project.artifactId}"
    provider: "fabric8"
    version: "${project.version}"
    group: "io.fabric8.kubeflix"
  name: "turbine-server"
spec:
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "turbine-server"
    provider: "fabric8"
    group: "io.fabric8.kubeflix"
  type: "LoadBalancer"
